# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0003_auto_20151231_0123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='description',
        ),
        migrations.RemoveField(
            model_name='text',
            name='description',
        ),
    ]
