# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0004_auto_20151231_0131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_text', models.TextField()),
                ('Image_ref', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_char', models.CharField(max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='text',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Text',
        ),
        migrations.AddField(
            model_name='content',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='options.Section'),
        ),
    ]
