# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0005_auto_20151231_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='description',
            field=models.CharField(default='Short description of content', max_length=40),
        ),
    ]
