# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0007_section_number_in_set'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='new cyoa', max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
