# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0008_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='intro',
            name='number_in_set',
            field=models.IntegerField(default=0),
        ),
    ]
