# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0009_intro_number_in_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
